// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOxROKXNUwTmH0lwX65C9Mxwjw07EwaI',
    appId: '1:743349386820:web:11d34e8cd7993fc5800611',
    messagingSenderId: '743349386820',
    projectId: 'chat-app-d7690',
    authDomain: 'chat-app-d7690.firebaseapp.com',
    storageBucket: 'chat-app-d7690.appspot.com',
    measurementId: 'G-L8G2YZCCF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3n-KE6QF4t2c5g1PrViNdclv-tG-qVo',
    appId: '1:743349386820:android:79985ec2a882d13f800611',
    messagingSenderId: '743349386820',
    projectId: 'chat-app-d7690',
    storageBucket: 'chat-app-d7690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkJ1-mM50T_GcPqhUewHE0XCC8Ls9gMKE',
    appId: '1:743349386820:ios:eecf5f512dd6e413800611',
    messagingSenderId: '743349386820',
    projectId: 'chat-app-d7690',
    storageBucket: 'chat-app-d7690.appspot.com',
    iosClientId: '743349386820-s7ku45fr19isjn7f15ldtr9i6o6qthm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkJ1-mM50T_GcPqhUewHE0XCC8Ls9gMKE',
    appId: '1:743349386820:ios:7df6387abdb8efba800611',
    messagingSenderId: '743349386820',
    projectId: 'chat-app-d7690',
    storageBucket: 'chat-app-d7690.appspot.com',
    iosClientId: '743349386820-23uqf91iqet3pnm9dmri1ukg2ip365k5.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodproject.RunnerTests',
  );
}
